### ISSUE TITLE
Wrong dimensions for `gpio_analog_pol[33]` in template def

### ISSUE THREAD

**Issue by kareefardi** [RTimothyEdwards/caravel_openframe_project#10]
`gpio_analog_pol[33]` is a met3 pin with width < met3 min width.

**Comment by RTimothyEdwards** [comment]
The pin used to be attached to metal2 and so it is the width of metal2, but the underlying metal3 layer is sufficiently wide.  It looks like I should have run extraction before generating the DEF so that it would pick up the rest of the net;  by not doing so, it output only the pin label and area.

**Comment by RTimothyEdwards** [comment]
But more to the point, all the other pins that had been on metal2 were resized to the full width of metal3, except `gpio_analog_pol[33]` was missed, which is a mistake.

**Comment by RTimothyEdwards** [comment]
@kareefardi :  Should be fixed now.
