### ISSUE TITLE
Missing pins in template def

### ISSUE THREAD

**Issue by kareefardi** [RTimothyEdwards/caravel_openframe_project#11]
The range `gpio_loopback_zero[15:23]` is missing in the template def file. In addition, some pins such as `gpio_loopback_one[0]` have two definitions. Each definition has a different location.

**Comment by kareefardi** [comment]
This appears to be the case as well in the mag file of the wrapper in caravel in `openframe_development` branch

**Comment by RTimothyEdwards** [comment]
They are correct in the `main` branch which indicates that the `main` branch is more up-to-date.  I'll need to regenerate the DEF from the version in `main`.  Although there may be conflicting changes between the two branches that I need to resolve.  I will look into it.

**Comment by kareefardi** [comment]
The main branch has the pin shift issue which was reported here https://github.com/efabless/caravel/issues/470. We need to settle on which one to use and continue with.

**Comment by RTimothyEdwards** [comment]
@kareefardi :  Should be fixed now.
