### ISSUE TITLE
Housekeeping reset register doesn't function 

### ISSUE THREAD

**Issue by M0stafaRady** [RTimothyEdwards/caravel_openframe_project#9]
Asserting the housekeeping reset register doesn't reset the CPU like caravel.

**Comment by RTimothyEdwards** [comment]
I just pushed a fix for this.  It moves the picosoc reset (wb_rst_i) from "resetb" to "core_rstn" from the reset synchronizer in caravel_clocking.  Thanks for the catch.  Please check that the modification doesn't have any unwanted side effects.

**Comment by M0stafaRady** [comment]
The fix works fine.
